export default {
  CREATE_USER_START  : 'CREATE_USER_START',
  CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
  CREATE_USER_FAIL   : 'CREATE_USER_FAIL',
  LOGIN_START        : 'LOGIN_START',
  LOGIN_SUCCESS      : 'LOGIN_SUCCESS',
  LOGIN_FAIL         : 'LOGIN_FAIL',
  LOGOUT_SUCCESS     : 'LOGOUT_SUCCESS',
  WELCOME_BACK       : 'WELCOME_BACK'

};